name: Nodejs
on:  
  push:
  pull_request:
 
jobs:
 Nodejs-1:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D]
    timeout-minutes: 350
    
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      run: echo "hello"
